#!/usr/bin/env node
// Regenerates docs/bundles.md and the bundle list inside README.md from the
// embedded catalog, so the docs can never drift from what dashkit installs.
//
//   node tools/gen-docs.mjs <skills-for-fabric clone>
//
// Skill descriptions come from Microsoft's SKILL.md front matter (MIT). For the
// data-goblin bundles only skill names are listed, each linking to its source:
// their licence does not allow copying the skills, and dashkit's own one-line
// bundle descriptions say what each is for.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

const upstream = resolve(process.argv[2] ?? ".");
const manifest = JSON.parse(readFileSync("internal/catalog/manifest.json", "utf8"));
const ref = manifest.source.ref;

// Just enough YAML for `description:` — plain scalars and folded blocks.
function description(skillMd) {
  const text = readFileSync(skillMd, "utf8").replace(/\r\n/g, "\n");
  const front = text.startsWith("---\n") ? text.slice(4, text.indexOf("\n---", 4)) : "";
  const lines = front.split("\n");
  const i = lines.findIndex((l) => l.startsWith("description:"));
  if (i < 0) return "";
  const inline = lines[i].slice("description:".length).trim();
  if (inline && !/^[>|]-?$/.test(inline)) return inline.replace(/^["']|["']$/g, "");
  const block = [];
  for (const l of lines.slice(i + 1)) {
    if (l && !l.startsWith(" ")) break;
    block.push(l.trim());
  }
  return block.join(" ").trim();
}

// The first sentence, which is how every upstream description opens: what the
// skill does. The trigger lists that follow are for the agent, not the reader.
function firstSentence(s) {
  const m = s.match(/^(.+?[.!?])(\s|$)/);
  return (m ? m[1] : s).replace(/\|/g, "\\|");
}

const msLink = (b, s) => `https://github.com/microsoft/skills-for-fabric/tree/${ref}/${b.dir}/skills/${s}`;
const goblinLink = (b, s) =>
  `https://github.com/${b.marketplace.repo}/tree/main/plugins/${b.marketplace.plugin}/skills/${s}`;

const vendored = manifest.bundles.filter((b) => b.kind === "vendored");
const market = manifest.bundles.filter((b) => b.kind === "marketplace");
const builtin = manifest.bundles.filter((b) => b.kind === "builtin");

function table(b) {
  const rows = b.skills.map((s) => {
    if (b.kind === "marketplace") return `| [\`${s}\`](${goblinLink(b, s)}) | |`;
    if (b.kind === "builtin") return `| [\`${s}\`](../bundles/${b.dir}/skills/${s}/SKILL.md) | ${b.description.replace(/\|/g, "\|")} |`;
    const md = join(upstream, b.dir, "skills", s, "SKILL.md");
    const d = existsSync(md) ? firstSentence(description(md)) : "";
    return `| [\`${s}\`](${msLink(b, s)}) | ${d} |`;
  });
  return ["| Skill | What it does |", "|---|---|", ...rows].join("\n");
}

function details(b, full) {
  const by = { marketplace: "data-goblin", builtin: "dashkit" }[b.kind] ?? "Microsoft";
  const hooks = b.hooks?.length ? ` · ${b.hooks.length} guardrail hooks` : "";
  const out = [
    "<details>",
    `<summary><strong>${b.title}</strong> &ensp;<code>${b.id}</code> &ensp;${by} · ${b.skills.length} skill${b.skills.length === 1 ? "" : "s"}${hooks}</summary>`,
    "",
    b.description,
    "",
  ];
  if (b.hooks?.length) {
    out.push("Checks that run automatically, without being asked:", "");
    for (const h of b.hooks) out.push(`- ${h}`);
    out.push("");
  }
  out.push(full ? table(b) : b.skills.map((s) => `\`${s}\``).join(" · "), "", "</details>", "");
  return out.join("\n");
}

// ---- docs/bundles.md ------------------------------------------------------
const doc = [
  "# Bundles",
  "",
  "<!-- Generated by tools/gen-docs.mjs from internal/catalog/manifest.json. Do not edit by hand. -->",
  "",
  "Every bundle dashkit can install, and where its version comes from:",
  "",
  `- **Copied by dashkit** (Cursor, VS Code, Codex, Gemini, and Claude Code with \`--host-plugin=false\`): Microsoft's bundles at the tag this dashkit release pins, \`${ref}\`.`,
  "- **Installed by the tool's own plugin manager** (Claude Code, Copilot CLI): whatever version that marketplace publishes now, and later updates arrive through the tool itself. data-goblin's bundles always install this way.",
  "",
  "> [!IMPORTANT]",
  "> Each installed skill competes for the agent's attention in every session its scope covers. Install the",
  "> bundles a project actually uses, into that project.",
  "",
  "## From Microsoft",
  "",
  `Copied at \`${ref}\` into tools without a plugin manager; Claude Code and Copilot CLI install the marketplace's current version instead.`,
  "",
  ...vendored.map((b) => details(b, true)),
  "## From dashkit",
  "",
  "dashkit's own, embedded in the binary and MIT-licensed. A workflow over the skills above rather than more of them.",
  "",
  ...builtin.map((b) => details(b, true)),
  "## From data-goblin",
  "",
  "Installed by Claude Code or Copilot CLI themselves. dashkit never copies these files: the project's",
  "licence does not allow it, and letting the host own them means their weekly updates and hooks keep",
  "working. Tools without a plugin manager are skipped with an explanation.",
  "",
  ...market.map((b) => details(b, true)),
].join("\n");
writeFileSync("docs/bundles.md", doc);

// ---- README block ------------------------------------------------------------
const readme = readFileSync("README.md", "utf8");
const start = "<!-- bundles:start -->";
const end = "<!-- bundles:end -->";
if (!readme.includes(start) || !readme.includes(end)) throw new Error("README.md has no bundles markers");
const block = [
  start,
  "",
  `**From Microsoft** — copied at the pinned tag \`${ref}\` into tools without a plugin manager; installed at the marketplace's current version by Claude Code and Copilot CLI.`,
  "",
  ...vendored.map((b) => details(b, false)),
  "**From dashkit** — its own workflow over those skills, embedded in the binary.",
  "",
  ...builtin.map((b) => details(b, false)),
  "**From data-goblin** — installed through Claude Code's or Copilot CLI's own plugin manager.",
  "",
  ...market.map((b) => details(b, false)),
  "Full tables with every skill's description: [docs/bundles.md](docs/bundles.md).",
  "",
  end,
].join("\n");
writeFileSync("README.md", readme.slice(0, readme.indexOf(start)) + block + readme.slice(readme.indexOf(end) + end.length));
console.log(`docs/bundles.md: ${manifest.bundles.length} bundles; README block updated`);
